version: "3.8"
services:
  postgres:
    container_name: "steamdb"
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      STEAMDB_VERSION: "1.0.0"
      USERS: "misha,egor,andrey,denis"
      QUERY_ATTEMPTS: 1000
    volumes:
      - ./analysis:/analysis/
      - ./migrations:/migrations/
      - ./migrations/init.sh:/docker-entrypoint-initdb.d/init.sh
      - steamdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  steamdb-data:
